<?php include"header.php"?>
<link rel="stylesheet" href="style/css/tabs.css" type="text/css">
<div class=table-box>
    <br>
        <h2 id="heading1">RESEARCH & CONSULTANCY</h2>
        <br>
            <div id='cssmenu1'class="dsw">
<ul>
    <li><a href='rnc.php'>Notices</a></li>
    <li class='active' ><a href='rnc_director.php'>Director</a></li>
    <li><a href='rnc_associate_director.php'>Associate Director</a></li>
   <li><a href='rnc_doctoral_research.php'>Doctoral Research</a></li>
   <li><a href='http://ipu.ac.in/researchcons/listofsupervisor.pdf'>Recognized Supervisor</a></li>
   <li><a href='rnc_contact_drc.php'>Contact DRC</a></li>
   <li><a href='phd_admission.php'>Ph.D./ M.Phil. Admissions</a></li>
</ul>
</div>
<br><br>
</div>
    <h1 align="center" ><strong>DIRECTOR</strong></h1>
  <!-- -->
   
   	
 
           <div class="uss_block1" id="uss_dean" style="width:100%;">
           <div id="uss_dean_image" ><img style="height:400px; width:300px;" src="style/rnc_dir.jpg" alt="Prof. P.C. Sharma"/></div>
           <div id="uss_dean_info">
           <p><br>
        <b>	Name:	</b>			Prof. P.C. Sharma<br><br>
		<b>Designation:	</b>	Professor<br><br>
		<b>	Subject :	</b>		 Biotechnology<br><br>
		<b>	School:	</b>		University School of BioTechnology<br><br>
		<b>	Educational Qualification:	</b>M.Sc. (Botany), M.Phil, Ph.D. in Agricultural Botany<br><br>
		<b>	Email:		</b>	prof.pcsharma@gmail.com, orgseciicb2013@ipu.ac.in <br><br>
		<b>	Phone:  	</b>	+91-11-25302301-04<br><br>
        <b>	Specialization		</b>Plant Molecular Biology, Crop Biotechnology <br><br>
        <b>	Field of Interest:		</b> Genetics, Plant Molecular Biology, Agricultural Biotechnology and Bioinformatics<br><br>
		<b>	Official Address:  	</b>	University School of Biotechnology, Guru Gobind Singh Indraprastha University, Dwarka, Sector-16C, Delhi- 110075</p>
        <br><br>
           </div>
           <div id="uss_dean_text">
		   <br><br><br><br>
           <h3>Teaching/Research Experience:</h3>
           <p style="text-align:justify;"><br>
Dr. P.C. Sharma did his M.Phil. & Ph.D in Agricultural Botany from Meerut University. He has over 25 years of teaching and research experience. Prior to joining this University in Nov. 2002, he served in Choudhury Charan Singh University, Meerut as a Lecturer and subsequently as a Reader in the Department of Agricultural Botany, and Coordinator, Department of Biotechnology. His main teaching and research areas cover genetics, plant molecular biology, agricultural biotechnology and bioinformatics. He has over 80 research publications to his credit. He has availed INSA-DFG International Exchange Fellowship in 1992, 1998 and 2009, and UNESCO Biotechnology Fellowship in 2000 at plant molecular biology unit of Frankfurt University, Frankfurt, Germany. During these visits, he worked on development of molecular markers for DNA fingerprinting, genome mapping and transcriptome analysis in chickpea. In 2002, he was awarded long term JSPS Invitation Fellowship for Research in Japan, which he availed at Iwate Biotechnology Research Centre, Kitakami, Japan to work in front line areas like Virus Induced Gene Silencing and Serial Analysis of Gene Expression. His group's most recent research on in silico mining and implication of microsatellites in genome evolution has been published in high ranking international journals and led to the development of two highly accessed microsatellite databases. He has undertaken a number of different research projects sanctioned by DBT, DRDO, ICAR, etc. He is a Fellow of the National Academy of Sciences, India.          </p>
           <h3>Selected Publications:</h3>
           <p style="text-align:justify;">
<ul><li><p><strong>1. Research Articles in Journals </strong><strong></strong></p>
            <p><strong>&nbsp;</strong>&#149;&nbsp; Qadri, H., <strong>Sharma, P. C </strong>., Qureshi, A., Singh, S. P. and Nehvi, F. A. (2012). DNA fingerprinting of saffron (Crocus sativus L.) by RAPD. VEGETOS <strong>25 </strong>: 194-197. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong>, Grover, A. and Roorkiwal, M. (2012). Purifying selection bias against microsatellites in gene rich segmental duplications in the rice genome. International Journal of Evolutionary Biology 2012: 8 pages doi: 10.1155/2012.970920. </p>
            <p>&#149;&nbsp; Grover, A. and <strong>Sharma, P. C. </strong> (2012). Tandem repetitions in transcriptomes of some Solanaceae species. American Journal of Molecular Biology <strong>2: </strong> 140-152. </p>
            <p>&#149;&nbsp; Roorkiwal, M. and <strong>Sharma, P. C. </strong> (2012). Sequence similarity based identification of abiotic stress responsive genes in chickpea ( <em>Cicer arietinum </em> L.) Bioinformation <strong>8(2) </strong>: 92-97. </p>
            <p>&#149;&nbsp; Grover, A., Aishwarya, V. and <strong>Sharma, P. C. </strong> (2012). Searching microsatellites in DNA sequences: approaches used and tools developed. Physiol. Mol. Biol. Plants <strong>18 </strong>: 11-19. </p>
            <p>&#149;&nbsp; Shokal, U. and <strong>Sharma, P. C. </strong> (2012). Implication of microsatellite instability in human gastric cancers. Indian J. Med. Res. <strong>135 </strong>: 599-613. </p>
            <p>&#149;&nbsp; Ghangal, R., Raghuvanshi, S. and <strong>Sharma, P. C. </strong> (2012). Expressed sequence tag based identification and expression analysis of some cold inducible elements in seabuckthorn ( <em>Hippophae rhamnoides </em> L.). Plant Physiol. Biochem. <strong>51 </strong>: 123-128. </p>
            <p>&#149;&nbsp; Roorkiwal, M. and <strong>Sharma, P. C. </strong> (2011). Mining functional microsatellite in legume unigenes. Bioinformation <strong>7(5) </strong>: 264-270. </p>
            <p>&#149;&nbsp; Shrivastava, D., Dalal, M., Nain, V., <strong>Sharma, P. C </strong>., and Kumar, P. A. ((2011). Targeted integration of <em>Bacillus thuringiensis </em> a-endotoxin <em>cry1Fa1 </em> in brinjal ( <em>Solanum melongena </em> L.). Current Trends in Biotechnology and Pharmacy <strong>5 </strong>: 1149-1156. </p>
            <p>&#149;&nbsp; Grover, A. and <strong>Sharma, P. C. </strong> (2011). Is spatial occurrence of microsatellites in the genome a determinant of their function and dynamics contributing to genome evolution? Curr. Sci. 100: 859-869. </p>
            <p>&#149;&nbsp; Shrivastava, D., Nain, V., Sahi, S., Verma, A., Sharma, P., <strong>Sharma, P. C. </strong> and Kumar, P. A. (2011). Insights from molecular modeling and dynamics simulations of pathogen resistance (R) protein from brinjal. Bioinformation <strong>5 </strong>: 326-330. </p>
            <p>&#149;&nbsp; Pandit, A., Rai, V., Sharma, T. R., <strong>Sharma, P. C. </strong>and Singh, N. K. (2011). Differentially expressed genes in sensitive and tolerant rice varieties in response to salt-stress. J. Plant Biochem. Biotechnol. <strong>20 </strong>: 149-154. </p>
            <p>&#149;&nbsp; Jain, A., Ghangal, R., Grover, A., Raghuvanshi, S. and <strong>Sharma, P. C. </strong> (2010). Development of EST-based new SSR markers in seabuckthorn. Physiol. Mol. Biol. Plants <strong>16 </strong>: 383-386. </p>
            <p>&#149;&nbsp; Pandit, A., Rai, V., Bal, S., Sinha, S. Kumar, V., Chauhan, M., Gautam, R., Singh, R., <strong>Sharma, P. C., </strong> Singh, A., Gaikwad, K., Sharma, T. R., Mohapatra, T. and Singh, N. K. (2010). Combining QTL mapping and transcriptome profiling of bulked RILs for identification of functional polymorphism for salt tolerance genes in rice ( <em>Oryza </em><em>sativa </em> L.). Mol. Genet. Genomics <strong>284 </strong>: 121-136. </p>
            <p>&#149;&nbsp; Ghangal, R., Raghuvanshi, S. and <strong>Sharma, P. C. </strong>(2009). Isolation of good quality RNA from a medicinal plant seabuckthorn, rich in secondary metabolites. Plant Physiol. Biochem. <strong>47 </strong>: 1113-1115. </p>
            <p>&#149;&nbsp; Grover, A., Ramesh, B. and <strong> Sharma, P. C. </strong> (2009). Development of microsatellite markers in potato and their transferability in some members of solanaceae. Physiol. Mol. Biol. Plants <strong> 15 </strong>: 343-358. </p>
            <p>&#149;&nbsp; Ammar, M. H. M., Pandit, A., Singh, R. K., Sameena, S., Chauhan, M. S., Singh, A. K., <strong>Sharma, P. C. </strong>, Gaikwad, K., Sharma, T.R., Mohapatra, T. and Singh, N.K. (2009). Mapping of QTLs controlling Na + , K + and Cl - ion concentrations in salt tolerant indica rice variety CSR27. J Plant Biochem. Biotechnol. 18: 139-150. </p>
            <p>&#149;&nbsp; Roorkiwal, M., Grover, A. and <strong>Sharma, P. C. </strong> (2009). Genome-wide analysis of conservation and divergence of microsatellites in rice. Mol. Genet. Genomics <strong>282 </strong>: 205-215 </p>
            <p>&#149;&nbsp; Chakraborty, A., Mishra, A. K. Soni, A., Regina, T., Mohil, R., Bhatnagar, D., Bhatnagar, A., Chintamani, C., <strong>Sharma, P. C </strong>. and Saxena, S. (2009). Vitamin D Receptor gene polymorphism(s) and breast cancer risk in North Indians. Cancer Detection and Prevention <strong>32 </strong>: 386-394 </p>
            <p>&#149;&nbsp; Ashutosh, Kumar, P., Kumar, D. V., <strong>Sharma, P. C. </strong>, Prakash, S. and Bhat, S. R. (2008). A novel <em>orf108 </em> co-transcribed with the <em>atpA </em> gene is associated with cytoplasmic male sterility in <em>Brassica juncea </em> carrying <em>Moricandia arvensis </em> cytoplasm. Plant Cell Physiol. <strong>49 </strong>: 284-289. </p>
            <p>&#149;&nbsp; Aishwarya, V. and <strong>Sharma, P. C </strong>. (2008) UgMicroSat <em>db </em> : database for mining microsatellites from unigenes. Nucleic Acids Research <strong>36 </strong>: D53-D56. doi:10.1093/nar/gkm811. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C., </strong> Grover, A. and Kahl, G. (2007). Mining microsatellites in eukaryotic genomes. Trends in Biotechnology <strong>25 </strong>: 490-498. </p>
            <p>&#149;&nbsp; Chauhan, T., Lal, K. K., Singh, R. K., Mohindra, V., Punia, P., Gopalakrishnan, A. <strong>Sharma, P. C. </strong> and Lakra, W. S. (2007). Evaluating genetic differentiation in wild populations of the Indian major carp, <em>Cirrhinus mrigala </em>(Hamilton-Buchanan, 1982): Evidence from allozyme and microsatellite markers. Aquaculture <strong>269 </strong>; 135-149. </p>
            <p>&#149;&nbsp; Chakraborty, A., Murthy, N. S., Chintamani, C., Bhatanager, D., Mohil, R. S., <strong>Sharma, P. C. </strong>and Saxena, S. (2007). CYP17 gene polymorphism and its association with high-risk North-Indian breast cancer patients. J. Human Genetics <strong>52 </strong>: 159-165. </p>
            <p>&#149;&nbsp; Aishwarya, V., Grover, A. and <strong>Sharma, P. C </strong>. (2007). EuMicroSat <em>db </em>: A databse for microsatellites in sequenced genomes of eukaryotes. BMC Genomics <strong>8 </strong>:225 doi:10.1186/1471-12164-8-225. </p>
            <p>&#149;&nbsp; Grover, A. and <strong>Sharma, P. C </strong>. (2007). Microsatellite motifs with moderate GC content are clustered around genes on <em>Arabidopsis thaliana </em> chromosome 2. In Silico Biol. <strong>7 </strong>: 201-213. </p>
            <p>&#149;&nbsp; Grover, A., Aishwarya, V. and <strong>Sharma P. C </strong>. (2007). Biased distribution of microsatellite motifs in the rice genome. Mol. Genet. Genomics <strong>277 </strong>: 469-480. </p>
            <p>&#149;&nbsp; Ashutosh, <strong>Sharma, P. C., </strong> Prakash, S. and Bhat S. R. (2007). Identification of AFLP markers linked to the male fertility restorer gene of CMS ( <em>Moricandia arvensis </em>) <em>Brassica juncea </em> and conversion to SCAR marker. Theor. Appl. Genet. <strong>114 </strong>: 385-392. </p>
            <p>&#149;&nbsp; Saxena, S., Chakraborty, A., Kaushal, M., Kotwal, S., Bhatanager, D., Mohil, R. S., Chintamani C., Aggarwal, A. K., Sharma, V. K., <strong>Sharma, P. C </strong>., Lenoir, G. Goldgar, D. E. and Szabo, C. I.(2006). Contribution of germline <em>BRCA1 </em> and <em>BRACA2 </em> sequence alterations to breast cancer in Northern India. BMC Medical Genetics <strong>7 </strong>:75 doi: 10.1186/1471-2356-7-75. </p>
            <p>&#149;&nbsp; Panguluri, S. K., Janaiah, K., Govil, J.N., Kumar, P. A., <strong></strong>and <strong> Sharma, P. C </strong>. (2006). AFLP fingerprinting in pigeonpea ( <em>Cajanus cajan </em> (L) Millsp.) and its wild relatives. Genetic Resources and Crop Evolution <strong>53 </strong>: 523-531. </p>
            <p>&#149;&nbsp; Luthra, S. K., <strong>Sharma, P. C </strong>. and Gopal, J. (2006). Identification of superior parents and crosses in potato breeding programme. Indian J. agric. Sci. <strong>76 </strong>:. 205 – 208. </p>
            <p>&#149;&nbsp; Luthra S. K., Gopal, J. and <strong>Sharma, P. C </strong>. (2005). Genetic divergence and its relationship with heterosis in potato. Potato J. <strong>32 </strong>: 37-42. </p>
            <p>&#149;&nbsp; Kashyap, M. K., Yadav, V., Sherawat, B. S., Jain, S., Kumari, S., Khullar, M., <strong>Sharma, P. C </strong>. and Nath, R. (2005). Different antioxidants status, total antioxidant power and free radicals in essential hypertension. Mol. Cell. Biochem. <strong>277 </strong>: 89-99. </p>
            <p>&#149;&nbsp; Nasir, K. H. B., Takahashi, Y., Ito, A., Saitoh, H., Matsumura, H., Kanzaki, H., Shimzu, T., Ito, M., Fujisawa, S., <strong>Sharma, P. C </strong>., Ohme-Takagi, M., Kamoun, S. and Terauchi, R. (2005). High-throughput <em>in planta </em> expression screening identifies a class II ethylene-responsive element binding factor-like protein that regulates plant cell death and no-host resistance. Plant J. <strong>43 </strong>: 491 – 505. </p>
            <p>&#149;&nbsp; Khandelwal, V. Dadlani. M., <strong>Sharma, P. C. </strong>, Pareek, A, Vashisht, V. and Sharma, S. P. (2005). Application of proteins and isoenzyme markers for DUS testing of Indian rice ( <em>Oryza sativa </em> L.) varieties. Indian J. Genet. <strong>64 </strong>: 261-264. </p>
            <p>&#149;&nbsp; Khandelwal, V., Dadlani,, M., <strong>Sharma, P. C. </strong>, Pareek, A, and Sharma, S. P. (2005). Molecular marker based co-efficient of percentage analysis for establishing distinctness in Indian Rice ( <em>Oryza sativa </em> L.) varieties. J. Plant Biochem. Biotechnol. <strong>14 </strong>: 135-139. </p>
            <p>&#149;&nbsp; Grover, A. and <strong>Sharma, P. C </strong>. (2004). Occurrence of Simple Sequence Repeats in potato ESTs is not random: An <em>in silico </em> study on distribution and length of single sequence repeats. Potato J. <strong>31 </strong>: 98-105. </p>
            <p>&#149;&nbsp; Panguluri, S. K., Sridhar, J., Jagadish, B., <strong>Sharma, P. C </strong> and Kumar, P. A (2005). Isolation and characterization of a green tissue-specific promoter from pigeonpea ( <em>Cajanus cajan </em>(L.) Millsp.). Indian J. Experimental Biology <strong>43 </strong>: 369-372. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C </strong>., Ito, A., Shimizu, T., Terauchi, R., Kamoun, S. and Saitoh, H. (2003). Virus-induced silencing of <em>WIPK </em> and <em>SIPK </em> genes reduces resistance to a bacterial pathogen, but has no effect on INF1-induced hypersensitive response (HR) in <em>Nicotiana benthamiana </em>. Mol. Genet. Genomics <strong>269 </strong>: 583-591. </p>
            <p>&#149;&nbsp; Kapoor, S., Singh, R. D., <strong>Sharma, P. C. </strong> and Khullar, M. (2002). Anaerobiosis induced virulence of <em>Salmonella typhi </em>. Indian J. Med. Res. <strong>115 </strong>: 184-188. </p>
            <p>&#149;&nbsp; Gaurav, Vats, P., Shyam, R., Suri, S., Kumria, M. M. L., Sridharan, K., <strong>Sharma, P. C. </strong> and Singh, S. N. (2001). Effect of pomegranate ( <em>Punica granatum </em> L ) juice on changes in tissue glutathione levels of rats exposed to high altitude hypoxia. Ancient Science of Life <strong>21 </strong>: 75-86. </p>
            <p>&#149;&nbsp; Luthra, S. K., <strong>Sharma, P. C. </strong> and Gopal, J. (2001). Inter-relationships between genetic parameters for tuber yield in potato. J. Indian Potato Assoc. <strong>28 </strong>: 15-17. </p>
            <p>&#149;&nbsp; Kaushik, T., Shyam, R., Vats, P., Suri, S., Kumria, M. M. L.., <strong>Sharma, P. C. </strong> and Singh, S. N. (2001). Glutathione metabolism in rats exposed to high-fluoride water and effect of spirulina treatment. Fluoride <strong>34 </strong>: 132-138. </p>
            <p>&#149;&nbsp; Yadav, U., Zende, R. J. and <strong>Sharma, P. C. </strong> (2000). Occurrence of <em>Salmonella </em> in some dehydrated vegetable samples. Indian J. Microbiology <strong>40 </strong>: 207-209. </p>
            <p>&#149;&nbsp; Singh, R., Tyagi, B. S. and <strong>Sharma, P. C. </strong> (2000). Identification of chromosomes involved in interchanges through translocation testers in pea. J. Cytol. Genet. <strong>1 (NS): </strong> 53-57. </p>
            <p>&#149;&nbsp; Winter, P., Pfaff, T., Udupa, S. M., Huttel, B., <strong>Sharma, P. C </strong>., Sahi, S., Arreguin- Espinoza, R., Weigand, F., Muehlbauer, F. J. and Kahl, G. (1999). Characterization and mapping of sequence tagged microsatellite sites in the chickpea ( <em>Cicer arietinum </em> L.) genome. Mol. Gen. Genet. <strong>262 </strong>: 90-101. </p>
            <p>&#149;&nbsp; Gupta, P. K., Varshney, R. K., <strong>Sharma, P. C. </strong> and Ramesh, B. (1999). Molecular markers and their applications in wheat breeding. Plant Breeding <strong>118 </strong>: 369-390. </p>
            <p>&#149;&nbsp; Gupta, P. K., Balyan, H. S., <strong>Sharma, P. C </strong>., Ramesh, B., Varshney, R. K., Roy, J. K. and Prasad, M. (1999). Development of molecular markers for wheat breeding at Meerut, a centre of wheat biotechnology network in India. Annu. Wheat Newsl. <strong>45: </strong>78-82. </p>
            <p>&#149;&nbsp; Prasad, M., Varshney, R. K., Kumar, A., Balyan, H. S., <strong>Sharma, P. C. </strong>, Edwards, K. J., Singh, H., Dhaliwal, H. S., Roy, J. K. and Gupta, P. K. (1999). A microsatellite marker associated with a QTL for grain protein content on chromosome arm 2DL of bread wheat. Theor. Appl. Genet. <strong>99 </strong>: 341-345. </p>
            <p>&#149;&nbsp; Singh, R. P., Garg, D. K. and <strong>Sharma, P. C. </strong> (1998). Character association in wheat ( <em>Triticum aestivum </em> L. EM. THELL). Indian J. Genet. <strong>58 </strong>: 219-221. </p>
            <p>&#149;&nbsp; Varshney, R. K., <strong>Sharma, P. C. </strong>, Gupta, P. K., Balyan, H. S., Ramesh, B., Roy, J. K., Kumar, A. and Sen, A. (1998). Low level of polymorphism detected by SSR probes in bread wheat. Plant Breeding <strong>117 </strong>: 182-184. </p>
            <p>&#149;&nbsp; Sen, A., Balyan, H. S., <strong>Sharma, P. C. </strong>, Ramesh, B., Kumar, A., Roy, J. K., Varshney, R. K. and Gupta, P. K. (1997). DNA amplification fingerprinting (DAF) as a new source of molecular markers in bread wheat. Wheat Information Service <strong>85 </strong>: 35-42. </p>
            <p>&#149;&nbsp; Singh, R. P., Garg, D. K. and <strong>Sharma, P. C. </strong> (1996). Genetic divergence in bread wheat. J. Cytol. Genet. <strong>31 </strong>: 101-103. </p>
            <p>&#149;&nbsp; Sharma, P. K., Garg, D. K. and <strong>Sharma, P. C. </strong> (1996). Genetic architecture of some quantitative characters in wheat. Indian J. Genet. <strong> 56 </strong>: 281-284. </p>
            <p>&#149;&nbsp; Gupta, P. K., Balyan, H. S., <strong>Sharma, P. C. </strong> and Ramesh, B. (1996). Microsatellites in plants: A new class of molecular markers. Curr. Sci. <strong>70 </strong>: 45-54. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong>, Huttel, B., Winter, P., Kahl, G., Gardner, R. C. and Weising, K. (1995). The potential of microsatellites for hybridization- and polymerase chain reaction- based DNA fingerprinting of chickpea ( <em>Cicer arietinum </em> L.) and related species. Electrophoresis <strong>16 </strong>: 1755-1761. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong>, Winter, P., Huttel, B., Bunger, T., Weigand, F., Weising, K. and Kahl, G. (1995). Abundance and polymorphism of di-, tri- and tetranucleotide tandem repeats in chickpea ( <em>Cicer arietinum </em> L.). Theor. Appl. Genet. <strong> 90 </strong>: 90-96. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Kumar, P. (1992). Intraspecific nuclear DNA variation in <em>Lathyrus sativus </em> L. Nucleus <strong>35 </strong>: 181-183. </p>
            <p>&#149;&nbsp; Luthra, S. K. and <strong>Sharma, P. C. </strong> (1990). Correlation and path analysis in lentils. LENS <strong>17 </strong>: 5-8. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Gupta, P. K. (1988). Numerical taxonomy in the genus <em>Cicer </em> L. Proc. Nat. Acad. Sci. INDIA <strong> 58 </strong>: 89-92. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Gupta, P. K. (1987). Colchicine induced autotetraploidy in chickpea ( <em>Cicer arietinum </em> L.). J. Cytol. Genet. <strong>22 </strong>: 58-66. <strong></strong></p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Luthra, S. K. (1987). Genetic divergence in lentil ( <em>Lens culinaris </em> Med.). Genet. Agr. <strong>41 </strong>: 349-359. </p>
            <p>&#149;&nbsp; Gupta, P. K., <strong>Sharma, P. C. </strong> and Singh, J. (1984). A triploid plant in lentils. LENS <strong>11 </strong>: 19-20. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong>, Verma, S. S. and Gupta, P. K. (1983). Autotetraploid lentils in the C 2 . LENS <strong>10 </strong>: 20-21. </p>
            <p>&#149;&nbsp; Gupta, P. K., <strong>Sharma, P. C. </strong>, Singh, J. and Verma, S. S. (1983). A new mutant (Globe) in lentils. LENS <strong>10 </strong>: 17-18. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Gupta, P. K. (1982). Genetic divergence in urdbean. Pulse Crops Newsletter <strong>2 </strong>: 31-32.&#149;&nbsp; <strong>Sharma, P. C. </strong> and Gupta, P. K. (1982). Karyotypes in some pulse crops. Nucleus <strong>25 </strong>: <strong></strong>181-185.            </p>
        </li>
          <li><p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Gupta, P. K. (1982). Chromosome associations in autotetraploid chickpea. International Chickpea Newsletter <strong> 6 </strong>: 3-4. </p>
            <p><strong>2. Full Papers in Conference Proceedings </strong></p>
            <p><strong>&nbsp;</strong>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Gupta, P. K. (1984). Pachytene chromosome morphology in <em>Cicer bijugum </em> rech <em> . </em> In : G. K. Manna and U. Sinha (eds) Perspectives in Cytology and Genetics <strong>4 </strong>: 485-489. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Gupta, P. K. (1986). Cytogenetics of legume genera <em>Cicer </em> L. and <em>Lens </em> L. In: P. K. Gupta and J. R. Bahl (eds). Genetics and Crop Improvement, pp. 321-340. </p>
            <p>&#149;&nbsp; Gupta, P. K. and <strong>Sharma, P. C. </strong> (1991). Cytogenetics of some legume crops. In: Proceedings Symposium on Grain Legumes, I.A.R.I., New Delhi, India, February 1991, pp. 1-24. </p>
            <p>&#149;&nbsp; <strong>Sharma P. C </strong>., Huttel, B., Winter, P., Bunger, T., Weigand, F., Weising K. and Kahl, G. (1993). Oligonucleotide fingerprinting in chickpea and identification of mol e cular markers linked with ascochyta resistance. In : International Workshop on Genomic Fingerprinting, Center for International Meetingsin Biology, Madrid (Spain), pp 61-62. </p>
            <p>&#149;&nbsp; Kahl, G., Ramser, J., Weising, K., Winter, P., Huttel, B., Geistlinger, J., <strong>Sharma, P. </strong>, Morjane, H., Harrabi, M., Weigand, F. and Saxena, M. C. (1995). Junk DNA, not so junky after all. In: Proceedings International Symposium on Induced Mutations and Molecular Techniques for Crop Improvements, IAEA, Vienna, Austria, February 1995, pp. 201-203. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong>, Winter, P., Bunger, T., Huttel, B., Weigand, F., Weising, K. and Kahl, G. (1996). Detection of DNA polymorphism in chickpea ( <em>Cicer arietinum </em> L.) using oligonucleotide probes. In: V. L. Chopra, M. S. Swaminathan and R. P. Sharma (eds). Proceedings of 2 nd Asia-Pacific Conference on Agricultural Biotechnology, Oxford and IBH, New Delhi, pp. 108-116. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong>, Winter, P., Bunger, T., Huttel, B. and Kahl, G. (1997). Expanding the repertoire of molecular markers for resistance breeding in chickpea. In: S. M. Udupa and F. Weigand (eds). DNA Markers and Breeding for resistance to Ascochyta Blight in Chickpea. Proceedings of the Symposium on “Application of DNA Fingerprinting for Crop Improvement: Marker-assisted Selection of Chickpea for Sustainable Agriculture in the Dry Areas”, Aleppo, Syria, ICARDA, pp. 175-198. </p>
            <p>&#149;&nbsp; Gupta, P. K., Balyan, H. S., <strong>Sharma, P. C. </strong> and Ramesh, B. (1998). Genetics and molecular biology of seed storage proteins in wheat. In: P. K. Gupta, S. P. Singh, H. S. Balyan, P. C. Sharma and B. Ramesh (eds), Genetics and Biotechnology in Crop Improvement, Rastogi &amp; Company, Meerut, pp.126-157. </p>
            <p>&#149;&nbsp; Balyan, H. S., <strong>Sharma, P. C. </strong>, Ramesh, B., Kumar, A., Varshney, R. K., Roy, J. K., Dhaliwal, H. S., Singh, H. and Gupta, P. K. (1998). Towards development of molecular markers for tagging genes for quality traits in bread wheat. In: A. E. Slinkard (ed). 9 th International Wheat Genetics Symposium, Aug. 2-7, 1998, Saskatoon, Canada, pp. 84-88. </p>
            <p>&#149;&nbsp; Luthra, S. K., <strong>Sharma, P. C. </strong> and Jai Gopal (2000). Performance of parents for true potato seed attributes. In: S. M. Paul khurana, G. S. Shekhawat, B. P. Singh and S. K. Pandey (eds.) Potato, Global Research &amp; Development. Proc. (Vol.1) Global Conference on Potato, New Delhi pp. 705-707. </p>
            <p>&#149;&nbsp; Grover, A. and <strong>Sharma, P. C. </strong> (2004). Isolation and characterization of microsatellites <em>in silico. </em>National workshop on “Current Trends in Bioinformatics”, Banasthali Vidyapith, Banasthali, Jan. 16-17, 2004. pp 12-27. </p>
            <p>&#149;&nbsp; Singh, N. K., <strong>Sharma, P. C </strong>., Reddy, A. R., Chattoo, B. and Tyagi, A. K. (2004). Structural and Functional Genomics. Base Papers, XV Genetics Congress Trust Symposium on Advancing Frontiers of Molecular Genetics: Exploring New Horizons, IARI, New Delhi, Jan. 21-22, 2004. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Grover, A. (2004). Bioinformatics: an overview. In Proc. 35 th Midterm Symposium on “Bioinformatics: Applications and Emerging Technologies”, IETE, Nagpur, Apr 3-4, pp 33-36. </p>
            <p>&#149;&nbsp; Grover, A., Tuteja, A., Aishwarya, V., Mittal, A., Gupta, G. and Sharma, P. C . (2005). <em>In silico </em>studies on occurrence of simple sequence repeats in various genomes. In: Proc. National workshop on “Current Trends in Bioinformatics”, Banasthali Vidyapith, Banasthali, Jan. 2005, pp 12-27. </p>
            <p>&#149;&nbsp; Coyne, C. J., Baum, M., Gaur, P. M., Timmerman-Vaughen, G. M., <strong>Sharma, P. C </strong>., Muehlbauer, F. J., McPhee, K. E., Chen, W., Pilet-Nayel, M. L., Brown, A. F., McGee, R. J., Udupa, S. M., Hamwiew, A. and Choumane, W. (2005). Application of molecular markers in cool season food legumes breeding. In: <em></em>M. C. Kharakwal (ed.). Food Legumes for Nutritional Security and Sustainable Agriculture, (Vol. 1) Proc. IV International Food Legume Conference (IFLRC-IV), IARI, October, 18-22, 2005 pp. 258-276. </p>
            <p>&#149;&nbsp; Jain, A., Ghangal, R., Chaudhary, S., Purty, R. S. and <strong>Sharma, P. C. </strong> (2011). Development of microsatellite markers in seabuckthorn. In: Proc. National Conference on Seabuckthorn: Emerging Trends in R &amp; D on Health Protection &amp; Environmental Conservation (V. Singh et al. eds) Palampur, Dec. 1-3, 2011, pp 48-53. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C., </strong> Chaudhary, S., Ghangal, R. and Purty, R. S. (2011). Transcriptome study and identification of genes differentially expressed during cold and freeze stress in seabuckthorn ( <em>Hippophae rhamnoides </em> L.) In: Proc. National Conference on Seabuckthorn: Emerging Trends in R &amp; D on Health Protection &amp; Environmental Conservation (V. Singh et al. eds) Palampur, Dec. 1-3, 2011, pp 54-60. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C., </strong>Jain, A., Chaudhary, S. (2012). Transcriptome analysis in seabuckthorn ( <em>Hippophae rhamnoides </em> L.), a medicinally important plant. In: Proc. International Conference on Environmental and Biological Sciences, Bangkok, Dec. 21-22, 2012, pp 21-24. </p>
            <p><strong>3. Chapters in Books </strong></p>
            <p><strong>&nbsp;</strong>&#149;&nbsp; <strong>Sharma, P. C. </strong>and Gupta, P. K. (1990). Molecular probes in plant genetic analysis. In: R. K. Behl and N. Maherchandani (eds). Trends in Crop Improvement, D.S.Printers, Hisar, India, pp. 100-114. </p>
            <p>&#149;&nbsp; Gupta, P. K. and <strong>Sharma, P. C. </strong> (1991). Cytogenetics and related aspects in some pulse crops. In: T. Tsuchiya, and Gupta, P. K.(eds) Chromosome Engineering in Plants: Genetics, Breeding, Evolution. Part B, Elsevier Sci. Publ.., The Netherlands, pp. 1-31. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong> and Varshney, R. K. (1998). Induced mutations in chickpea improvement. In: B. A. Siddiqui and S. Khan (eds). Mutagenesis and <em>In Vitro </em> Mutation Breeding in Crop Plants, Kalyani Publishers, India. pp. 58-68. </p>
            <p>&#149;&nbsp; Winter, P., Staginnus, C. <strong>Sharma. P. C. </strong> and Kahl, G. (2003). Organisation and genetic mapping of the chickpea genome. In: P. K. Jaiwal and R. P. Singh (eds). Improvement Strategies for Leguminosae Biotechnology. Kluwer Academic Publishers, Dordrecht, The Netherlands pp 303-351. </p>
            <p>&#149;&nbsp; <strong>Sharma, P. C. </strong>, Matsumura, H. and Terauchi, R. (2007). Use of serial analysis of gene expression (SAGE) for transcript profiling in plants. In: RK Varshney and R Tuberosa (eds) Genomics-Assisted Crop Improvement: Vol. 1: Genomics Approaches and Platforms, Springer pp. 227-244. </p>
            <p>&#149;&nbsp; Shrivastava, D., <strong>Sharma, P. C. </strong> and Kumar, P. A. (2008). Gene targeting in higher plants. In: A. Kumar and S.K. Sopory (eds) Recent Advances in Plant Biotechnology and its Applications. I. K. Publishers Pvt. Ltd. India, pp. 78-92. </p>
            <p>&#149;&nbsp; Ganghal, R., Raghuvanshi, S. and <strong>Sharma, P. C. </strong> (2008). Exploring seabuckthorn genome using molecular tools. In: S. K. Dwivedi, T. Perimalazagan, S. B. Singh and Z. Ahmad (eds.) Seabuckthorn- The Wonder Plant. SSPH Publishers, Delhi , pp. 347 – 371. </p>
            <p>&#149;&nbsp; Grover, A., Jain, A. and <strong>Sharma, P.C. </strong> (2010) Microsatellite Markers: Potential and Opportunities in Medicinal Plants. In: Medicinal Plant Biotechnology (ed.) Rajesh Arora, CAB International, Oxon, United Kingdom pp. 71-92. </p>
            <p>&#149;&nbsp; Jain, A., Chaudhary, S. and <strong>Sharma, P. C. </strong> (2013) Application of DNA technologies for seabuckthorn improvement. In: Seabuckthorn – A Multipurpose Wonder Plant: Advancement in Technologies (ed.) V. Singh </p>
            <p><strong>4. Editing of Proceedings of the Symposium </strong></p>
            <p><strong></strong>Associate Editor, Genetics and Biotechnology in <strong></strong>Crop Improvement . Proc. Symp.“Genetics and Biotechnology in Crop Improvement”, (eds. P.K. Gupta, S.P. Singh, H.S. Balyan, <strong>P.C. Sharma </strong> and B. Ramesh) Feb. 1997, Department of Agricultural Botany, Ch. Charan Singh University, Meerut. Rastogi Publications, Meerut, India. 414 pp. </p>
            <p><strong>5. Other Publications </strong></p>
            <p>Abstracts, extended summaries of more than 50 research papers presented in conferences, </p>
            <p>Seminars, symposia, contact programmes, etc. held in India and abroad. </p>
            <p><strong>6. Construction of Microsatellite Databases </strong></p>
            <p>We have constructed following two important databases for mining microsatellites in the sequences eukaryotic genomes and unigenes and retrieving related information. The two online databases are frequently accessed by scientific community interested in microsatellites. </p>
            <p><strong>EuMicroSat <em>db </em>: </strong>Adatabse for microsatellites in the sequenced genomes of eukaryotes <strong></strong></p>
            <p><strong>UgMicroSat <em>db </em>: </strong>A database for mining microsatellites in unigenes </p>
            <p>The above databases can be accessed free at <a href="http://ipu.ac.in/usbt/EuMicroSatdb.htm">http://ipu.ac.in/usbt/EuMicroSat <em>db </em>.htm </a> and <a href="http://ipu.ac.in/usbt/UgMicroSatdb.htm">http://ipu.ac.in/usbt/UgMicroSat <em>db </em>.htm </a></p>
            <p><strong>&nbsp;</strong><strong>7. EST sequences submitted to NCBI </strong></p>
            <p>My laboratory has submitted two batches of 2788 and 1043 Seabuckthorn ESTs to the NCBI ESTdb in 2008 under a DRDO project sanctioned to me. More ESTs are likely to be submitted soon. This is the only set of ESTs ever submitted for this important plant species. The analysis of first set has shown about 50 sequences that can be involved in cold tolerance. Further analysis is in progress. </p>
            <p>Recently, we have extended our seabuckthorn transcriptomics project and have undertaken large scale EST-sequencing. We hope to submit over 20.000 ESTs in near future. Data analysis is under progress. </p>
            <p><strong>&nbsp; </strong></p>
          </li>
        </ul>
          
           </div>
           
           </div>                 

<!-------Footer-------------------->     
<?php include"footer1.php"?>